// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwfn0eu6uhUwm_y9iTOwpbN9enipIhoZA',
    appId: '1:408075613759:web:efe682f69d4f0abd9eaa8a',
    messagingSenderId: '408075613759',
    projectId: 'gudangin-35213',
    authDomain: 'gudangin-35213.firebaseapp.com',
    storageBucket: 'gudangin-35213.firebasestorage.app',
    measurementId: 'G-LGBLCJ1WEX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG7PGfqdIqVP4EcbZ4Si03m2XG-HLGUlo',
    appId: '1:408075613759:android:c49945654699b8209eaa8a',
    messagingSenderId: '408075613759',
    projectId: 'gudangin-35213',
    storageBucket: 'gudangin-35213.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6nUJFGv-_7cyozbP06xgy3saxcRzKV34',
    appId: '1:408075613759:ios:ecf6b7795d7920c89eaa8a',
    messagingSenderId: '408075613759',
    projectId: 'gudangin-35213',
    storageBucket: 'gudangin-35213.firebasestorage.app',
    iosBundleId: 'com.example.gudangin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6nUJFGv-_7cyozbP06xgy3saxcRzKV34',
    appId: '1:408075613759:ios:ecf6b7795d7920c89eaa8a',
    messagingSenderId: '408075613759',
    projectId: 'gudangin-35213',
    storageBucket: 'gudangin-35213.firebasestorage.app',
    iosBundleId: 'com.example.gudangin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwfn0eu6uhUwm_y9iTOwpbN9enipIhoZA',
    appId: '1:408075613759:web:5abe2f1376ec63a69eaa8a',
    messagingSenderId: '408075613759',
    projectId: 'gudangin-35213',
    authDomain: 'gudangin-35213.firebaseapp.com',
    storageBucket: 'gudangin-35213.firebasestorage.app',
    measurementId: 'G-615HX5YE6W',
  );
}
